[package]
name = "rust-bincode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*" }
bincode = "*"
serde-pickle = "1.0"
base64 = "*"
rust-crypto = "*"
rand = "*"
openssl = "*"